name: Build and Push Compiled Static Packages

on:
  release:
    types: [published] # Only runs when a release is published

permissions:
  contents: write # Required to upload assets to the release

jobs:
  build-and-upload-static:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Yarn
        run: npm install --global yarn

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Build project
        run: bash ./scripts/web-release.sh

      - name: Upload Packaged Files
        uses: jaywcjlove/github-action-upload-assets@main
        with:
          tag: ${{ github.event.release.tag_name }}
          asset-path: '["release/*"]'
